name: Build E2E Test Event Writer
workflow_dispatch: none

permissions:
  contents: read
  id-token: write

jobs:
  retina-win-e2e-bpf-images:
    name: Build E2E Test Event Writer
    runs-on: windows-2022

    strategy:
      matrix:
        platform: ["windows"]
        arch: ["x64"]

    variables:
      # Path to the solution file relative to the root of the project.
      MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64'
      GITHUB_WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: llvm downgrade
        run: |
          choco install -y llvm --version 11.0.1 --allow-downgrade
          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Event-Writer
        shell: pwsh
        run: |
          $MSBUILD_PATH = 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64'
          $SOLUTION_FILE_PATH: ${{ github.workspace }}/test/e2e/tools/event-writer/event_writer.sln
          "$(MSBUILD_PATH)\msbuild.exe" /m /p:Configuration=Release /p:Platform=x64 /restore "$(SOLUTION_FILE_PATH)"
