name: Build E2E Test Event Writer
on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:


permissions:
  contents: read
  id-token: write

env:
  EVENT_WRITER_PATH: "${{ github.workspace }}/test/e2e/tools/event-writer/"

jobs:
  retina-win-e2e-bpf-images:
    name: Build E2E Test Event Writer
    runs-on: windows-2022

    strategy:
      matrix:
        platform: ["windows"]
        arch: ["x64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: llvm downgrade
        run: |
          choco install -y llvm --version 11.0.1 --allow-downgrade
          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Nuget Restore
        shell: cmd
        run: |
          dir
          nuget restore event_writer.sln
        working-directory: ${{ env.EVENT_WRITER_PATH }}

      - name: Build Event-Writer
        shell: pwsh
        run: |
          & msbuild.exe /m /p:Configuration=Release /p:Platform=x64 /restore event_writer.sln
        working-directory: ${{ env.EVENT_WRITER_PATH }}