name: Build Images

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: [manifests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup go
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: go.mod
      - run: go version

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Run E2E Tests
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        shell: bash
        run: |
          set -euo pipefail
          go test -v ./test/e2e/. -timeout 60m -tags=e2e -count=1  -args -image-tag=$(make version) -image-registry=${{ vars.ACR_NAME }}  -image-namespace=${{ github.repository}}